# Compiler definitions
CC = gcc
CCFLAGS = -c -Wall $(addprefix -D,$(DEFINES)) -I$(INCLUDE_DIR) $(MAKEFILE_DEPS_FLAGS)
MAKEFILE_DEPS_FLAGS = -MMD -MP
DEFINES =
LDFLAGS =

# Helper programs
MKDIR_P = mkdir -p

# Directories
SOURCE_DIR = src
INCLUDE_DIR = include
OBJ_DIR = obj
BIN_DIR = bin

# Files
EXECUTABLE = $(BIN_DIR)/matasano
INCLUDES = $(wildcard $(INCLUDE_DIR)/*.h)
SOURCES = $(wildcard $(SOURCE_DIR)/*.c)
OBJECTS = $(SOURCES:$(SOURCE_DIR)/%.c=$(OBJ_DIR)/%.o)
MAGIC_HEADER = $(INCLUDE_DIR)/magic.h
DEPS = $(OBJECTS:.o=.d)

# Phony Targets
.PHONY: dirs all clean

all: dirs $(OBJECTS) $(EXECUTABLE)
	@echo "All done."

clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)
	@echo "Cleaned."

dirs: $(OBJ_DIR) $(BIN_DIR)

# Real Targets
$(EXECUTABLE): $(OBJECTS)
	@echo "Linking $(EXECUTABLE)..."
	$(CC) $(LDFLAGS) $(OBJECTS) -o $(EXECUTABLE)
	@echo "Done.\n"

#TODO: can the pattern matching look nicer?
$(OBJ_DIR)/%.o: $(SOURCE_DIR)/%.c $(MAGIC_HEADER)
	@echo "Compiling $< ..."
	$(CC) $(CCFLAGS) $< -o $@
	@echo "Done.\n"

$(MAGIC_HEADER): create_magic_header.py
	python create_magic_header.py

$(OBJ_DIR) $(BIN_DIR):
	@echo "Creating output folder..."
	$(MKDIR_P) $@;
	@echo "Done.\n"

# Include dependency targets generated by (-MMD -MP) flags
-include $(DEPS)
