# Compiler definitions
CC = gcc
CCFLAGS = -c -Wall $(addprefix -D,$(DEFINES)) -I$(INCLUDE_DIR) $(MAKEFILE_DEPS_FLAGS)
MAKEFILE_DEPS_FLAGS = -MMD -MP
DEFINES =
LDFLAGS =

# Helper programs
MKDIR_P = mkdir -p

# Directories
SOURCE_DIR = src
INCLUDE_DIR = include
OBJ_DIR = obj
BIN_DIR = bin

# Files
EXECUTABLE = $(BIN_DIR)/matasano
INCLUDES = $(wildcard $(INCLUDE_DIR)/*.h)
SOURCES = $(wildcard $(SOURCE_DIR)/*.c)
OBJECTS = $(SOURCES:$(SOURCE_DIR)/%.c=$(OBJ_DIR)/%.o)
MAGIC_HEADER = $(INCLUDE_DIR)/magic.h
MAGIC_HEADER_GENERATOR_SCRIPT = create_magic_header.py
DEPS = $(OBJECTS:.o=.d)

# Phony Targets
.PHONY: dirs all clean

all: dirs $(OBJECTS) $(EXECUTABLE)
	@printf "All done.\n"

clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR) $(MAGIC_HEADER)
	@printf "Cleaned.\n"

dirs: $(OBJ_DIR) $(BIN_DIR)

# Real Targets
$(EXECUTABLE): $(OBJECTS)
	@printf "Linking $(EXECUTABLE)...\n"
	$(CC) $(LDFLAGS) $(OBJECTS) -o $(EXECUTABLE)
	@printf "Done.\n\n"

#TODO: can the pattern matching look nicer?
$(OBJ_DIR)/%.o: $(SOURCE_DIR)/%.c $(MAGIC_HEADER)
	@printf "Compiling $< ...\n"
	$(CC) $(CCFLAGS) $< -o $@
	@printf "Done.\n\n"

$(MAGIC_HEADER): $(MAGIC_HEADER_GENERATOR_SCRIPT)
	@printf "Generating magic header...\n"
	python $(MAGIC_HEADER_GENERATOR_SCRIPT)
	@printf "Done.\n\n"

$(OBJ_DIR) $(BIN_DIR):
	@printf "Creating output folder...\n"
	$(MKDIR_P) $@;
	@printf "Done.\n\n"

# Include dependency targets generated by (-MMD -MP) flags
-include $(DEPS)
